name: yaoyao

services:
  db:
    image: postgres:18
    container_name: yaoyao-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yaoyao
    ports:
      - 5434:5432
    volumes:
      - ./build/db:/data/db
    networks:
      - yaoyao-network

  redis:
    image: redis:8.4-alpine
    container_name: yaoyao-redis
    restart: always
    command: ["redis-server", "--requirepass", "pass"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - yaoyao-network

  minio:
    image: quay.io/minio/minio:latest
    container_name: yaoyao-minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - yaoyao-network
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  yaoyao-network:
    driver: bridge

volumes:
  redis-data:
  minio_data:
