/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSignedUrlParams,
  SignUrlResponseDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getSignedUrl = (
    params: GetSignedUrlParams,
 signal?: AbortSignal
) => {


      return customInstance<SignUrlResponseDto>(
      {url: `/api/images/sign-url`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetSignedUrlQueryKey = (params?: GetSignedUrlParams,) => {
    return [
    `/api/images/sign-url`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSignedUrlQueryOptions = <TData = Awaited<ReturnType<typeof getSignedUrl>>, TError = unknown>(params: GetSignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSignedUrlQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSignedUrl>>> = ({ signal }) => getSignedUrl(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSignedUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getSignedUrl>>>
export type GetSignedUrlQueryError = unknown


export function useGetSignedUrl<TData = Awaited<ReturnType<typeof getSignedUrl>>, TError = unknown>(
 params: GetSignedUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getSignedUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSignedUrl<TData = Awaited<ReturnType<typeof getSignedUrl>>, TError = unknown>(
 params: GetSignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSignedUrl>>,
          TError,
          Awaited<ReturnType<typeof getSignedUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSignedUrl<TData = Awaited<ReturnType<typeof getSignedUrl>>, TError = unknown>(
 params: GetSignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSignedUrl<TData = Awaited<ReturnType<typeof getSignedUrl>>, TError = unknown>(
 params: GetSignedUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSignedUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSignedUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






