/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AdminAuthResponseDto,
  AdminLoginDto,
  PinAuthResponseDto,
  PinDto
} from '../model';

import { customInstance } from '../../common/axios';




export const verifyAdmin = (
    adminLoginDto: AdminLoginDto,
 signal?: AbortSignal
) => {


      return customInstance<AdminAuthResponseDto>(
      {url: `/api/auth/admin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminLoginDto, signal
    },
      );
    }



export const getVerifyAdminMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAdmin>>, TError,{data: AdminLoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyAdmin>>, TError,{data: AdminLoginDto}, TContext> => {

const mutationKey = ['verifyAdmin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyAdmin>>, {data: AdminLoginDto}> = (props) => {
          const {data} = props ?? {};

          return  verifyAdmin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifyAdminMutationResult = NonNullable<Awaited<ReturnType<typeof verifyAdmin>>>
    export type VerifyAdminMutationBody = AdminLoginDto
    export type VerifyAdminMutationError = unknown

    export const useVerifyAdmin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAdmin>>, TError,{data: AdminLoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyAdmin>>,
        TError,
        {data: AdminLoginDto},
        TContext
      > => {
      return useMutation(getVerifyAdminMutationOptions(options), queryClient);
    }
    export const verifyPin = (
    pinDto: PinDto,
 signal?: AbortSignal
) => {


      return customInstance<PinAuthResponseDto>(
      {url: `/api/auth/pin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pinDto, signal
    },
      );
    }



export const getVerifyPinMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPin>>, TError,{data: PinDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyPin>>, TError,{data: PinDto}, TContext> => {

const mutationKey = ['verifyPin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyPin>>, {data: PinDto}> = (props) => {
          const {data} = props ?? {};

          return  verifyPin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type VerifyPinMutationResult = NonNullable<Awaited<ReturnType<typeof verifyPin>>>
    export type VerifyPinMutationBody = PinDto
    export type VerifyPinMutationError = unknown

    export const useVerifyPin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPin>>, TError,{data: PinDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyPin>>,
        TError,
        {data: PinDto},
        TContext
      > => {
      return useMutation(getVerifyPinMutationOptions(options), queryClient);
    }
