/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkCreateTableDto,
  CreateTableDto,
  GetTablesParams,
  IdsDto,
  PersonDto,
  ReassignTablesDto,
  TableDto,
  TableListDto,
  TablePositionDto,
  UpdateTableDetailsDto,
  UpdateTableDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getTables = (
    params?: GetTablesParams,
 signal?: AbortSignal
) => {


      return customInstance<TableListDto>(
      {url: `/api/tables`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetTablesQueryKey = (params?: GetTablesParams,) => {
    return [
    `/api/tables`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTablesQueryOptions = <TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(params?: GetTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTablesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTables>>> = ({ signal }) => getTables(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTablesQueryResult = NonNullable<Awaited<ReturnType<typeof getTables>>>
export type GetTablesQueryError = unknown


export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
 params: undefined |  GetTablesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTables>>,
          TError,
          Awaited<ReturnType<typeof getTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
 params?: GetTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTables>>,
          TError,
          Awaited<ReturnType<typeof getTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
 params?: GetTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
 params?: GetTablesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTablesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createTable = (
    createTableDto: CreateTableDto,
 signal?: AbortSignal
) => {


      return customInstance<TableDto>(
      {url: `/api/tables`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTableDto, signal
    },
      );
    }



export const getCreateTableMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{data: CreateTableDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{data: CreateTableDto}, TContext> => {

const mutationKey = ['createTable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTable>>, {data: CreateTableDto}> = (props) => {
          const {data} = props ?? {};

          return  createTable(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTableMutationResult = NonNullable<Awaited<ReturnType<typeof createTable>>>
    export type CreateTableMutationBody = CreateTableDto
    export type CreateTableMutationError = unknown

    export const useCreateTable = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTable>>, TError,{data: CreateTableDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTable>>,
        TError,
        {data: CreateTableDto},
        TContext
      > => {
      return useMutation(getCreateTableMutationOptions(options), queryClient);
    }
    export const getStagedTables = (

 signal?: AbortSignal
) => {


      return customInstance<TableDto[]>(
      {url: `/api/tables/staged`, method: 'GET', signal
    },
      );
    }




export const getGetStagedTablesQueryKey = () => {
    return [
    `/api/tables/staged`
    ] as const;
    }


export const getGetStagedTablesQueryOptions = <TData = Awaited<ReturnType<typeof getStagedTables>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStagedTablesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStagedTables>>> = ({ signal }) => getStagedTables(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStagedTablesQueryResult = NonNullable<Awaited<ReturnType<typeof getStagedTables>>>
export type GetStagedTablesQueryError = unknown


export function useGetStagedTables<TData = Awaited<ReturnType<typeof getStagedTables>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStagedTables>>,
          TError,
          Awaited<ReturnType<typeof getStagedTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStagedTables<TData = Awaited<ReturnType<typeof getStagedTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStagedTables>>,
          TError,
          Awaited<ReturnType<typeof getStagedTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStagedTables<TData = Awaited<ReturnType<typeof getStagedTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStagedTables<TData = Awaited<ReturnType<typeof getStagedTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStagedTables>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStagedTablesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTableById = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<TableDto>(
      {url: `/api/tables/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetTableByIdQueryKey = (id: string,) => {
    return [
    `/api/tables/${id}`
    ] as const;
    }


export const getGetTableByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableById>>> = ({ signal }) => getTableById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTableByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTableById>>>
export type GetTableByIdQueryError = unknown


export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableById>>,
          TError,
          Awaited<ReturnType<typeof getTableById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableById>>,
          TError,
          Awaited<ReturnType<typeof getTableById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTableByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const updateTable = (
    id: string,
    updateTableDto: UpdateTableDto,
 signal?: AbortSignal
) => {


      return customInstance<TableDto>(
      {url: `/api/tables/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTableDto, signal
    },
      );
    }



export const getUpdateTableMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTable>>, TError,{id: string;data: UpdateTableDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTable>>, TError,{id: string;data: UpdateTableDto}, TContext> => {

const mutationKey = ['updateTable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTable>>, {id: string;data: UpdateTableDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTable(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTableMutationResult = NonNullable<Awaited<ReturnType<typeof updateTable>>>
    export type UpdateTableMutationBody = UpdateTableDto
    export type UpdateTableMutationError = unknown

    export const useUpdateTable = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTable>>, TError,{id: string;data: UpdateTableDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTable>>,
        TError,
        {id: string;data: UpdateTableDto},
        TContext
      > => {
      return useMutation(getUpdateTableMutationOptions(options), queryClient);
    }
    export const deleteTable = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteTableMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTable>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTable>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTable'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTable>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTable(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTableMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTable>>>

    export type DeleteTableMutationError = unknown

    export const useDeleteTable = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTable>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTable>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteTableMutationOptions(options), queryClient);
    }
    export const getTablePeople = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<PersonDto[]>(
      {url: `/api/tables/${id}/people`, method: 'GET', signal
    },
      );
    }




export const getGetTablePeopleQueryKey = (id: string,) => {
    return [
    `/api/tables/${id}/people`
    ] as const;
    }


export const getGetTablePeopleQueryOptions = <TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTablePeopleQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTablePeople>>> = ({ signal }) => getTablePeople(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTablePeopleQueryResult = NonNullable<Awaited<ReturnType<typeof getTablePeople>>>
export type GetTablePeopleQueryError = unknown


export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTablePeople>>,
          TError,
          Awaited<ReturnType<typeof getTablePeople>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTablePeople>>,
          TError,
          Awaited<ReturnType<typeof getTablePeople>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTablePeopleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const bulkCreateTables = (
    bulkCreateTableDto: BulkCreateTableDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkCreateTableDto, signal
    },
      );
    }



export const getBulkCreateTablesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTables>>, TError,{data: BulkCreateTableDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTables>>, TError,{data: BulkCreateTableDto}, TContext> => {

const mutationKey = ['bulkCreateTables'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkCreateTables>>, {data: BulkCreateTableDto}> = (props) => {
          const {data} = props ?? {};

          return  bulkCreateTables(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BulkCreateTablesMutationResult = NonNullable<Awaited<ReturnType<typeof bulkCreateTables>>>
    export type BulkCreateTablesMutationBody = BulkCreateTableDto
    export type BulkCreateTablesMutationError = unknown

    export const useBulkCreateTables = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTables>>, TError,{data: BulkCreateTableDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkCreateTables>>,
        TError,
        {data: BulkCreateTableDto},
        TContext
      > => {
      return useMutation(getBulkCreateTablesMutationOptions(options), queryClient);
    }
    export const bulkDeleteTables = (
    idsDto: IdsDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/bulk-delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: idsDto, signal
    },
      );
    }



export const getBulkDeleteTablesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkDeleteTables>>, TError,{data: IdsDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkDeleteTables>>, TError,{data: IdsDto}, TContext> => {

const mutationKey = ['bulkDeleteTables'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkDeleteTables>>, {data: IdsDto}> = (props) => {
          const {data} = props ?? {};

          return  bulkDeleteTables(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BulkDeleteTablesMutationResult = NonNullable<Awaited<ReturnType<typeof bulkDeleteTables>>>
    export type BulkDeleteTablesMutationBody = IdsDto
    export type BulkDeleteTablesMutationError = unknown

    export const useBulkDeleteTables = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkDeleteTables>>, TError,{data: IdsDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkDeleteTables>>,
        TError,
        {data: IdsDto},
        TContext
      > => {
      return useMutation(getBulkDeleteTablesMutationOptions(options), queryClient);
    }
    export const reassignTables = (
    reassignTablesDto: ReassignTablesDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/reassign`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reassignTablesDto, signal
    },
      );
    }



export const getReassignTablesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reassignTables>>, TError,{data: ReassignTablesDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof reassignTables>>, TError,{data: ReassignTablesDto}, TContext> => {

const mutationKey = ['reassignTables'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reassignTables>>, {data: ReassignTablesDto}> = (props) => {
          const {data} = props ?? {};

          return  reassignTables(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReassignTablesMutationResult = NonNullable<Awaited<ReturnType<typeof reassignTables>>>
    export type ReassignTablesMutationBody = ReassignTablesDto
    export type ReassignTablesMutationError = unknown

    export const useReassignTables = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reassignTables>>, TError,{data: ReassignTablesDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reassignTables>>,
        TError,
        {data: ReassignTablesDto},
        TContext
      > => {
      return useMutation(getReassignTablesMutationOptions(options), queryClient);
    }
    export const updateTableDetails = (
    id: string,
    updateTableDetailsDto: UpdateTableDetailsDto,
 signal?: AbortSignal
) => {


      return customInstance<TableDto>(
      {url: `/api/tables/${id}/details`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTableDetailsDto, signal
    },
      );
    }



export const getUpdateTableDetailsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableDetails>>, TError,{id: string;data: UpdateTableDetailsDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTableDetails>>, TError,{id: string;data: UpdateTableDetailsDto}, TContext> => {

const mutationKey = ['updateTableDetails'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTableDetails>>, {id: string;data: UpdateTableDetailsDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTableDetails(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTableDetailsMutationResult = NonNullable<Awaited<ReturnType<typeof updateTableDetails>>>
    export type UpdateTableDetailsMutationBody = UpdateTableDetailsDto
    export type UpdateTableDetailsMutationError = unknown

    export const useUpdateTableDetails = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableDetails>>, TError,{id: string;data: UpdateTableDetailsDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTableDetails>>,
        TError,
        {id: string;data: UpdateTableDetailsDto},
        TContext
      > => {
      return useMutation(getUpdateTableDetailsMutationOptions(options), queryClient);
    }
    export const updateTablePosition = (
    id: string,
    tablePositionDto: TablePositionDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/${id}/position`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: tablePositionDto, signal
    },
      );
    }



export const getUpdateTablePositionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTablePosition>>, TError,{id: string;data: TablePositionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTablePosition>>, TError,{id: string;data: TablePositionDto}, TContext> => {

const mutationKey = ['updateTablePosition'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTablePosition>>, {id: string;data: TablePositionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTablePosition(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTablePositionMutationResult = NonNullable<Awaited<ReturnType<typeof updateTablePosition>>>
    export type UpdateTablePositionMutationBody = TablePositionDto
    export type UpdateTablePositionMutationError = unknown

    export const useUpdateTablePosition = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTablePosition>>, TError,{id: string;data: TablePositionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTablePosition>>,
        TError,
        {id: string;data: TablePositionDto},
        TContext
      > => {
      return useMutation(getUpdateTablePositionMutationOptions(options), queryClient);
    }
