/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../common/axios';




export const getTables = (

 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables`, method: 'GET', signal
    },
      );
    }




export const getGetTablesQueryKey = () => {
    return [
    `/api/tables`
    ] as const;
    }


export const getGetTablesQueryOptions = <TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTablesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTables>>> = ({ signal }) => getTables(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTablesQueryResult = NonNullable<Awaited<ReturnType<typeof getTables>>>
export type GetTablesQueryError = unknown


export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTables>>,
          TError,
          Awaited<ReturnType<typeof getTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTables>>,
          TError,
          Awaited<ReturnType<typeof getTables>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTables<TData = Awaited<ReturnType<typeof getTables>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTables>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTablesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTableById = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetTableByIdQueryKey = (id: string,) => {
    return [
    `/api/tables/${id}`
    ] as const;
    }


export const getGetTableByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableById>>> = ({ signal }) => getTableById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTableByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTableById>>>
export type GetTableByIdQueryError = unknown


export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableById>>,
          TError,
          Awaited<ReturnType<typeof getTableById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableById>>,
          TError,
          Awaited<ReturnType<typeof getTableById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTableById<TData = Awaited<ReturnType<typeof getTableById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTableByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTablePeople = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/tables/${id}/people`, method: 'GET', signal
    },
      );
    }




export const getGetTablePeopleQueryKey = (id: string,) => {
    return [
    `/api/tables/${id}/people`
    ] as const;
    }


export const getGetTablePeopleQueryOptions = <TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTablePeopleQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTablePeople>>> = ({ signal }) => getTablePeople(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTablePeopleQueryResult = NonNullable<Awaited<ReturnType<typeof getTablePeople>>>
export type GetTablePeopleQueryError = unknown


export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTablePeople>>,
          TError,
          Awaited<ReturnType<typeof getTablePeople>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTablePeople>>,
          TError,
          Awaited<ReturnType<typeof getTablePeople>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTablePeople<TData = Awaited<ReturnType<typeof getTablePeople>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTablePeople>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTablePeopleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






