/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BatchCreateOrderDto,
  CreateOrderDto,
  GetOrdersParams,
  UpdateOrderDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getOrders = (
    params?: GetOrdersParams,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/orders`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetOrdersQueryKey = (params?: GetOrdersParams,) => {
    return [
    `/api/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getOrders>>, TError = unknown>(params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrders>>> = ({ signal }) => getOrders(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrders>>>
export type GetOrdersQueryError = unknown


export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = unknown>(
 params: undefined |  GetOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrders>>,
          TError,
          Awaited<ReturnType<typeof getOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = unknown>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrders>>,
          TError,
          Awaited<ReturnType<typeof getOrders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = unknown>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = unknown>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createOrder = (
    createOrderDto: CreateOrderDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/orders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrderDto, signal
    },
      );
    }



export const getCreateOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: CreateOrderDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: CreateOrderDto}, TContext> => {

const mutationKey = ['createOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrder>>, {data: CreateOrderDto}> = (props) => {
          const {data} = props ?? {};

          return  createOrder(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>
    export type CreateOrderMutationBody = CreateOrderDto
    export type CreateOrderMutationError = unknown

    export const useCreateOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrder>>, TError,{data: CreateOrderDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrder>>,
        TError,
        {data: CreateOrderDto},
        TContext
      > => {
      return useMutation(getCreateOrderMutationOptions(options), queryClient);
    }
    export const createOrderBatch = (
    batchCreateOrderDto: BatchCreateOrderDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/orders/batch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: batchCreateOrderDto, signal
    },
      );
    }



export const getCreateOrderBatchMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrderBatch>>, TError,{data: BatchCreateOrderDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createOrderBatch>>, TError,{data: BatchCreateOrderDto}, TContext> => {

const mutationKey = ['createOrderBatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrderBatch>>, {data: BatchCreateOrderDto}> = (props) => {
          const {data} = props ?? {};

          return  createOrderBatch(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOrderBatchMutationResult = NonNullable<Awaited<ReturnType<typeof createOrderBatch>>>
    export type CreateOrderBatchMutationBody = BatchCreateOrderDto
    export type CreateOrderBatchMutationError = unknown

    export const useCreateOrderBatch = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrderBatch>>, TError,{data: BatchCreateOrderDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrderBatch>>,
        TError,
        {data: BatchCreateOrderDto},
        TContext
      > => {
      return useMutation(getCreateOrderBatchMutationOptions(options), queryClient);
    }
    export const updateOrder = (
    id: string,
    updateOrderDto: UpdateOrderDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/orders/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateOrderDto, signal
    },
      );
    }



export const getUpdateOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: string;data: UpdateOrderDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: string;data: UpdateOrderDto}, TContext> => {

const mutationKey = ['updateOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrder>>, {id: string;data: UpdateOrderDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrder(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrder>>>
    export type UpdateOrderMutationBody = UpdateOrderDto
    export type UpdateOrderMutationError = unknown

    export const useUpdateOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrder>>, TError,{id: string;data: UpdateOrderDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrder>>,
        TError,
        {id: string;data: UpdateOrderDto},
        TContext
      > => {
      return useMutation(getUpdateOrderMutationOptions(options), queryClient);
    }
    export const deleteOrder = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/orders/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteOrderMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrder>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteOrder(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrder>>>

    export type DeleteOrderMutationError = unknown

    export const useDeleteOrder = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrder>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrder>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteOrderMutationOptions(options), queryClient);
    }
