/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateFoodDto,
  GetFoodsParams,
  GetFoodsResponseDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getFoods = (
    params?: GetFoodsParams,
 signal?: AbortSignal
) => {


      return customInstance<GetFoodsResponseDto>(
      {url: `/api/foods`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetFoodsQueryKey = (params?: GetFoodsParams,) => {
    return [
    `/api/foods`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetFoodsQueryOptions = <TData = Awaited<ReturnType<typeof getFoods>>, TError = unknown>(params?: GetFoodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoodsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFoods>>> = ({ signal }) => getFoods(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFoodsQueryResult = NonNullable<Awaited<ReturnType<typeof getFoods>>>
export type GetFoodsQueryError = unknown


export function useGetFoods<TData = Awaited<ReturnType<typeof getFoods>>, TError = unknown>(
 params: undefined |  GetFoodsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoods>>,
          TError,
          Awaited<ReturnType<typeof getFoods>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFoods<TData = Awaited<ReturnType<typeof getFoods>>, TError = unknown>(
 params?: GetFoodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFoods>>,
          TError,
          Awaited<ReturnType<typeof getFoods>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFoods<TData = Awaited<ReturnType<typeof getFoods>>, TError = unknown>(
 params?: GetFoodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetFoods<TData = Awaited<ReturnType<typeof getFoods>>, TError = unknown>(
 params?: GetFoodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFoods>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFoodsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createFood = (
    createFoodDto: CreateFoodDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/foods`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createFoodDto, signal
    },
      );
    }



export const getCreateFoodMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFood>>, TError,{data: CreateFoodDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createFood>>, TError,{data: CreateFoodDto}, TContext> => {

const mutationKey = ['createFood'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFood>>, {data: CreateFoodDto}> = (props) => {
          const {data} = props ?? {};

          return  createFood(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFoodMutationResult = NonNullable<Awaited<ReturnType<typeof createFood>>>
    export type CreateFoodMutationBody = CreateFoodDto
    export type CreateFoodMutationError = unknown

    export const useCreateFood = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFood>>, TError,{data: CreateFoodDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFood>>,
        TError,
        {data: CreateFoodDto},
        TContext
      > => {
      return useMutation(getCreateFoodMutationOptions(options), queryClient);
    }
