/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AddPresetItemDto,
  CreatePresetDto,
  GetPresetMenuByIdParams,
  GetPresetMenusParams,
  PresetMenuDto,
  UpdatePresetDto,
  UpdatePresetItemDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getPresetMenus = (
    params?: GetPresetMenusParams,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto[]>(
      {url: `/api/preset-menus`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetPresetMenusQueryKey = (params?: GetPresetMenusParams,) => {
    return [
    `/api/preset-menus`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPresetMenusQueryOptions = <TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(params?: GetPresetMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPresetMenusQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPresetMenus>>> = ({ signal }) => getPresetMenus(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPresetMenusQueryResult = NonNullable<Awaited<ReturnType<typeof getPresetMenus>>>
export type GetPresetMenusQueryError = unknown


export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
 params: undefined |  GetPresetMenusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenus>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
 params?: GetPresetMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenus>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
 params?: GetPresetMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
 params?: GetPresetMenusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPresetMenusQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createPresetMenu = (
    createPresetDto: CreatePresetDto,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPresetDto, signal
    },
      );
    }



export const getCreatePresetMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext> => {

const mutationKey = ['createPresetMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPresetMenu>>, {data: CreatePresetDto}> = (props) => {
          const {data} = props ?? {};

          return  createPresetMenu(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePresetMenuMutationResult = NonNullable<Awaited<ReturnType<typeof createPresetMenu>>>
    export type CreatePresetMenuMutationBody = CreatePresetDto
    export type CreatePresetMenuMutationError = unknown

    export const useCreatePresetMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPresetMenu>>,
        TError,
        {data: CreatePresetDto},
        TContext
      > => {
      return useMutation(getCreatePresetMenuMutationOptions(options), queryClient);
    }
    export const getPresetMenuById = (
    id: string,
    params?: GetPresetMenuByIdParams,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus/${id}`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetPresetMenuByIdQueryKey = (id: string,
    params?: GetPresetMenuByIdParams,) => {
    return [
    `/api/preset-menus/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPresetMenuByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(id: string,
    params?: GetPresetMenuByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPresetMenuByIdQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPresetMenuById>>> = ({ signal }) => getPresetMenuById(id,params, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPresetMenuByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPresetMenuById>>>
export type GetPresetMenuByIdQueryError = unknown


export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string,
    params: undefined |  GetPresetMenuByIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenuById>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenuById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string,
    params?: GetPresetMenuByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenuById>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenuById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string,
    params?: GetPresetMenuByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string,
    params?: GetPresetMenuByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPresetMenuByIdQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const updatePresetMenu = (
    id: string,
    updatePresetDto: UpdatePresetDto,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePresetDto, signal
    },
      );
    }



export const getUpdatePresetMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenu>>, TError,{id: string;data: UpdatePresetDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenu>>, TError,{id: string;data: UpdatePresetDto}, TContext> => {

const mutationKey = ['updatePresetMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePresetMenu>>, {id: string;data: UpdatePresetDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePresetMenu(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePresetMenuMutationResult = NonNullable<Awaited<ReturnType<typeof updatePresetMenu>>>
    export type UpdatePresetMenuMutationBody = UpdatePresetDto
    export type UpdatePresetMenuMutationError = unknown

    export const useUpdatePresetMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenu>>, TError,{id: string;data: UpdatePresetDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePresetMenu>>,
        TError,
        {id: string;data: UpdatePresetDto},
        TContext
      > => {
      return useMutation(getUpdatePresetMenuMutationOptions(options), queryClient);
    }
    export const deletePresetMenu = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/preset-menus/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeletePresetMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePresetMenu>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePresetMenu>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePresetMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePresetMenu>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePresetMenu(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePresetMenuMutationResult = NonNullable<Awaited<ReturnType<typeof deletePresetMenu>>>

    export type DeletePresetMenuMutationError = unknown

    export const useDeletePresetMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePresetMenu>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePresetMenu>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeletePresetMenuMutationOptions(options), queryClient);
    }
    export const addPresetMenuItem = (
    id: string,
    addPresetItemDto: AddPresetItemDto,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus/${id}/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addPresetItemDto, signal
    },
      );
    }



export const getAddPresetMenuItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPresetMenuItem>>, TError,{id: string;data: AddPresetItemDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addPresetMenuItem>>, TError,{id: string;data: AddPresetItemDto}, TContext> => {

const mutationKey = ['addPresetMenuItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPresetMenuItem>>, {id: string;data: AddPresetItemDto}> = (props) => {
          const {id,data} = props ?? {};

          return  addPresetMenuItem(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddPresetMenuItemMutationResult = NonNullable<Awaited<ReturnType<typeof addPresetMenuItem>>>
    export type AddPresetMenuItemMutationBody = AddPresetItemDto
    export type AddPresetMenuItemMutationError = unknown

    export const useAddPresetMenuItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPresetMenuItem>>, TError,{id: string;data: AddPresetItemDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addPresetMenuItem>>,
        TError,
        {id: string;data: AddPresetItemDto},
        TContext
      > => {
      return useMutation(getAddPresetMenuItemMutationOptions(options), queryClient);
    }
    export const updatePresetMenuItem = (
    id: string,
    variantId: string,
    updatePresetItemDto: UpdatePresetItemDto,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus/${id}/items/${variantId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePresetItemDto, signal
    },
      );
    }



export const getUpdatePresetMenuItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenuItem>>, TError,{id: string;variantId: string;data: UpdatePresetItemDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenuItem>>, TError,{id: string;variantId: string;data: UpdatePresetItemDto}, TContext> => {

const mutationKey = ['updatePresetMenuItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePresetMenuItem>>, {id: string;variantId: string;data: UpdatePresetItemDto}> = (props) => {
          const {id,variantId,data} = props ?? {};

          return  updatePresetMenuItem(id,variantId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePresetMenuItemMutationResult = NonNullable<Awaited<ReturnType<typeof updatePresetMenuItem>>>
    export type UpdatePresetMenuItemMutationBody = UpdatePresetItemDto
    export type UpdatePresetMenuItemMutationError = unknown

    export const useUpdatePresetMenuItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePresetMenuItem>>, TError,{id: string;variantId: string;data: UpdatePresetItemDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePresetMenuItem>>,
        TError,
        {id: string;variantId: string;data: UpdatePresetItemDto},
        TContext
      > => {
      return useMutation(getUpdatePresetMenuItemMutationOptions(options), queryClient);
    }
    export const removePresetMenuItem = (
    id: string,
    variantId: string,
 signal?: AbortSignal
) => {


      return customInstance<PresetMenuDto>(
      {url: `/api/preset-menus/${id}/items/${variantId}`, method: 'DELETE', signal
    },
      );
    }



export const getRemovePresetMenuItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePresetMenuItem>>, TError,{id: string;variantId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removePresetMenuItem>>, TError,{id: string;variantId: string}, TContext> => {

const mutationKey = ['removePresetMenuItem'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removePresetMenuItem>>, {id: string;variantId: string}> = (props) => {
          const {id,variantId} = props ?? {};

          return  removePresetMenuItem(id,variantId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemovePresetMenuItemMutationResult = NonNullable<Awaited<ReturnType<typeof removePresetMenuItem>>>

    export type RemovePresetMenuItemMutationError = unknown

    export const useRemovePresetMenuItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePresetMenuItem>>, TError,{id: string;variantId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removePresetMenuItem>>,
        TError,
        {id: string;variantId: string},
        TContext
      > => {
      return useMutation(getRemovePresetMenuItemMutationOptions(options), queryClient);
    }
