/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatePresetDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getPresetMenus = (

 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/preset-menus`, method: 'GET', signal
    },
      );
    }




export const getGetPresetMenusQueryKey = () => {
    return [
    `/api/preset-menus`
    ] as const;
    }


export const getGetPresetMenusQueryOptions = <TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPresetMenusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPresetMenus>>> = ({ signal }) => getPresetMenus(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPresetMenusQueryResult = NonNullable<Awaited<ReturnType<typeof getPresetMenus>>>
export type GetPresetMenusQueryError = unknown


export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenus>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenus>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPresetMenus<TData = Awaited<ReturnType<typeof getPresetMenus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenus>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPresetMenusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createPresetMenu = (
    createPresetDto: CreatePresetDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/preset-menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPresetDto, signal
    },
      );
    }



export const getCreatePresetMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext> => {

const mutationKey = ['createPresetMenu'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPresetMenu>>, {data: CreatePresetDto}> = (props) => {
          const {data} = props ?? {};

          return  createPresetMenu(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePresetMenuMutationResult = NonNullable<Awaited<ReturnType<typeof createPresetMenu>>>
    export type CreatePresetMenuMutationBody = CreatePresetDto
    export type CreatePresetMenuMutationError = unknown

    export const useCreatePresetMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetMenu>>, TError,{data: CreatePresetDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPresetMenu>>,
        TError,
        {data: CreatePresetDto},
        TContext
      > => {
      return useMutation(getCreatePresetMenuMutationOptions(options), queryClient);
    }
    export const getPresetMenuById = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/preset-menus/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetPresetMenuByIdQueryKey = (id: string,) => {
    return [
    `/api/preset-menus/${id}`
    ] as const;
    }


export const getGetPresetMenuByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPresetMenuByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPresetMenuById>>> = ({ signal }) => getPresetMenuById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPresetMenuByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPresetMenuById>>>
export type GetPresetMenuByIdQueryError = unknown


export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenuById>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenuById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPresetMenuById>>,
          TError,
          Awaited<ReturnType<typeof getPresetMenuById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPresetMenuById<TData = Awaited<ReturnType<typeof getPresetMenuById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPresetMenuById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPresetMenuByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






