/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type AppConfigDtoType = typeof AppConfigDtoType[keyof typeof AppConfigDtoType];


export const AppConfigDtoType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  json: 'json',
} as const;
