/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface AssignPresetDto {
  /**
     * Preset menu id, or null to clear
     * @nullable
     */
  presetMenuId?: string | null;
}
