/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { BatchOrderItemDto } from './batchOrderItemDto';

export interface BatchCreateOrderDto {
  tableId: string;
  items: BatchOrderItemDto[];
  splitAll?: boolean;
  personIds?: string[];
}
