/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface CreateTableDto {
  /** Seat an existing physical slot into the event. Omit to mint a new slot. */
  slotId?: string;
  /** Name for a newly minted slot; ignored when slotId is given */
  name?: string;
  capacity?: number;
  /** Create as a staged table for the next event */
  isStaging?: boolean;
}
