/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface CreateOrderDto {
  tableId: string;
  variantId: string;
  quantity?: number;
  /** Shared by the whole table (default) */
  splitAll?: boolean;
  /** People the cost is split across when splitAll is false */
  personIds?: string[];
}
