/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface CreatePersonDto {
  name: string;
  /** Table to seat this person at */
  tableId: string;
}
