/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { PresetFoodDto } from './presetFoodDto';

export interface CreatePresetDto {
  price: number;
  isActive?: boolean;
  foods?: PresetFoodDto[];
}
