/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface CreateCategoryDto {
  key: string;
  name: string;
  description?: string;
  /** Locale the name/description are written in */
  lang?: string;
  isAvailable?: boolean;
}
