/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface EventStatsDto {
  tables: number;
  occupied: number;
  people: number;
  orders: number;
}
