/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { EventStatsDto } from './eventStatsDto';

export interface EventSummaryDto {
  id: string;
  pin: string;
  /** @nullable */
  name?: string | null;
  isActive: boolean;
  /** @nullable */
  presetMenuId?: string | null;
  createdAt: string;
  stats: EventStatsDto;
}
