/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { FoodVariantDto } from './foodVariantDto';

export interface FoodDetailDto {
  id: string;
  name: string;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  categoryId: string | null;
  isAvailable: boolean;
  variants: FoodVariantDto[];
}
