/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface FoodItemDto {
  id: string;
  name: string;
  /** @nullable */
  imageUrl: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  categoryId: string | null;
  isAvailable: boolean;
  isPopular: boolean;
}
