/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type GetFeedbackByEventSort = typeof GetFeedbackByEventSort[keyof typeof GetFeedbackByEventSort];


export const GetFeedbackByEventSort = {
  recent: 'recent',
  top: 'top',
} as const;
