/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { GetFeedbackSort } from './getFeedbackSort';

export type GetFeedbackParams = {
sort?: GetFeedbackSort;
count?: number;
page?: number;
};
