/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type GetFoodsSortBy = typeof GetFoodsSortBy[keyof typeof GetFoodsSortBy];


export const GetFoodsSortBy = {
  name: 'name',
  price: 'price',
  popular: 'popular',
} as const;
