/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { GetFeedbackByEventSort } from './getFeedbackByEventSort';

export type GetFeedbackByEventParams = {
eventId: string;
sort?: GetFeedbackByEventSort;
count?: number;
page?: number;
};
