/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type GetFoodsSortOrder = typeof GetFoodsSortOrder[keyof typeof GetFoodsSortOrder];


export const GetFoodsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
