/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type GetPopularItemsScope = typeof GetPopularItemsScope[keyof typeof GetPopularItemsScope];


export const GetPopularItemsScope = {
  event: 'event',
  all: 'all',
} as const;
