/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { HealthResponseDtoStatus } from './healthResponseDtoStatus';
import type { HealthServicesDto } from './healthServicesDto';
import type { SystemMetricsDto } from './systemMetricsDto';

export interface HealthResponseDto {
  status: HealthResponseDtoStatus;
  system: SystemMetricsDto;
  services: HealthServicesDto;
}
