/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { OrderSplitDto } from './orderSplitDto';

export interface OrderResponseDto {
  id: string;
  tableId: string;
  variantId: string;
  /** @nullable */
  eventId: string | null;
  quantity: number;
  price: number;
  splitAll: boolean;
  foodName: string;
  variantLabel: string;
  splits: OrderSplitDto[];
  createdAt: string;
  updatedAt: string;
}
