/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface PersonRowDto {
  id: string;
  name: string;
  /** @nullable */
  tableName?: string | null;
  ordered: string[];
  /** @nullable */
  note?: string | null;
}
