/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface PublishEventDto {
  name?: string;
  /** Preset menu assigned to the whole event */
  presetMenuId?: string;
}
