/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface ReassignTablesDto {
  ids: string[];
  /**
     * Target event id, or null to move back to staging
     * @nullable
     */
  eventId?: string | null;
}
