/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export type ServiceStatusDtoStatus = typeof ServiceStatusDtoStatus[keyof typeof ServiceStatusDtoStatus];


export const ServiceStatusDtoStatus = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
} as const;
