/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import type { ServiceStatusDtoStatus } from './serviceStatusDtoStatus';

export interface ServiceStatusDto {
  status: ServiceStatusDtoStatus;
  latency?: number;
  /** @nullable */
  message?: string | null;
}
