/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface TableSlotDto {
  id: string;
  no: number;
  name: string;
  /** @nullable */
  x?: number | null;
  /** @nullable */
  y?: number | null;
  defaultCapacity: number;
  isActive: boolean;
}
