/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface TableDto {
  id: string;
  name: string;
  capacity: number;
  seated: number;
  isStaging: boolean;
  no: number;
  /** @nullable */
  x?: number | null;
  /** @nullable */
  y?: number | null;
  /** @nullable */
  tableLeaderId?: string | null;
  /** @nullable */
  eventId?: string | null;
}
