/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateConfigDto {
  /** Raw value, stored as-is and parsed by the row's type */
  value: string;
}
