/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */

export interface UpdateFoodVariantDto {
  label?: string;
  /** @nullable */
  price?: number | null;
  currency?: string;
  isSeasonal?: boolean;
  isAvailable?: boolean;
  /** Locale the label is written in */
  lang?: string;
}
