/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPeopleListParams,
  GetPopularItemsParams,
  PeopleListDto,
  PopularItemDto,
  TableTotalDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getPopularItems = (
    params?: GetPopularItemsParams,
 signal?: AbortSignal
) => {


      return customInstance<PopularItemDto[]>(
      {url: `/api/stats/popular`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetPopularItemsQueryKey = (params?: GetPopularItemsParams,) => {
    return [
    `/api/stats/popular`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPopularItemsQueryOptions = <TData = Awaited<ReturnType<typeof getPopularItems>>, TError = unknown>(params?: GetPopularItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPopularItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPopularItems>>> = ({ signal }) => getPopularItems(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPopularItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getPopularItems>>>
export type GetPopularItemsQueryError = unknown


export function useGetPopularItems<TData = Awaited<ReturnType<typeof getPopularItems>>, TError = unknown>(
 params: undefined |  GetPopularItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularItems>>,
          TError,
          Awaited<ReturnType<typeof getPopularItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPopularItems<TData = Awaited<ReturnType<typeof getPopularItems>>, TError = unknown>(
 params?: GetPopularItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPopularItems>>,
          TError,
          Awaited<ReturnType<typeof getPopularItems>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPopularItems<TData = Awaited<ReturnType<typeof getPopularItems>>, TError = unknown>(
 params?: GetPopularItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPopularItems<TData = Awaited<ReturnType<typeof getPopularItems>>, TError = unknown>(
 params?: GetPopularItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPopularItems>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPopularItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getTableTotals = (

 signal?: AbortSignal
) => {


      return customInstance<TableTotalDto[]>(
      {url: `/api/stats/tables`, method: 'GET', signal
    },
      );
    }




export const getGetTableTotalsQueryKey = () => {
    return [
    `/api/stats/tables`
    ] as const;
    }


export const getGetTableTotalsQueryOptions = <TData = Awaited<ReturnType<typeof getTableTotals>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableTotalsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableTotals>>> = ({ signal }) => getTableTotals(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTableTotalsQueryResult = NonNullable<Awaited<ReturnType<typeof getTableTotals>>>
export type GetTableTotalsQueryError = unknown


export function useGetTableTotals<TData = Awaited<ReturnType<typeof getTableTotals>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableTotals>>,
          TError,
          Awaited<ReturnType<typeof getTableTotals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableTotals<TData = Awaited<ReturnType<typeof getTableTotals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableTotals>>,
          TError,
          Awaited<ReturnType<typeof getTableTotals>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableTotals<TData = Awaited<ReturnType<typeof getTableTotals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTableTotals<TData = Awaited<ReturnType<typeof getTableTotals>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableTotals>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTableTotalsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getPeopleList = (
    params?: GetPeopleListParams,
 signal?: AbortSignal
) => {


      return customInstance<PeopleListDto>(
      {url: `/api/stats/people`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetPeopleListQueryKey = (params?: GetPeopleListParams,) => {
    return [
    `/api/stats/people`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPeopleListQueryOptions = <TData = Awaited<ReturnType<typeof getPeopleList>>, TError = unknown>(params?: GetPeopleListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPeopleListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPeopleList>>> = ({ signal }) => getPeopleList(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPeopleListQueryResult = NonNullable<Awaited<ReturnType<typeof getPeopleList>>>
export type GetPeopleListQueryError = unknown


export function useGetPeopleList<TData = Awaited<ReturnType<typeof getPeopleList>>, TError = unknown>(
 params: undefined |  GetPeopleListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeopleList>>,
          TError,
          Awaited<ReturnType<typeof getPeopleList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPeopleList<TData = Awaited<ReturnType<typeof getPeopleList>>, TError = unknown>(
 params?: GetPeopleListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPeopleList>>,
          TError,
          Awaited<ReturnType<typeof getPeopleList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPeopleList<TData = Awaited<ReturnType<typeof getPeopleList>>, TError = unknown>(
 params?: GetPeopleListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPeopleList<TData = Awaited<ReturnType<typeof getPeopleList>>, TError = unknown>(
 params?: GetPeopleListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPeopleList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPeopleListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






