/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkCreateTableSlotDto,
  CreateTableSlotDto,
  GetTableSlotsParams,
  TablePositionDto,
  TableSlotDto,
  UpdateTableSlotDto
} from '../model';

import { customInstance } from '../../common/axios';




export const getTableSlots = (
    params?: GetTableSlotsParams,
 signal?: AbortSignal
) => {


      return customInstance<TableSlotDto[]>(
      {url: `/api/table-slots`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetTableSlotsQueryKey = (params?: GetTableSlotsParams,) => {
    return [
    `/api/table-slots`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTableSlotsQueryOptions = <TData = Awaited<ReturnType<typeof getTableSlots>>, TError = unknown>(params?: GetTableSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableSlotsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableSlots>>> = ({ signal }) => getTableSlots(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTableSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getTableSlots>>>
export type GetTableSlotsQueryError = unknown


export function useGetTableSlots<TData = Awaited<ReturnType<typeof getTableSlots>>, TError = unknown>(
 params: undefined |  GetTableSlotsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableSlots>>,
          TError,
          Awaited<ReturnType<typeof getTableSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableSlots<TData = Awaited<ReturnType<typeof getTableSlots>>, TError = unknown>(
 params?: GetTableSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableSlots>>,
          TError,
          Awaited<ReturnType<typeof getTableSlots>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableSlots<TData = Awaited<ReturnType<typeof getTableSlots>>, TError = unknown>(
 params?: GetTableSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTableSlots<TData = Awaited<ReturnType<typeof getTableSlots>>, TError = unknown>(
 params?: GetTableSlotsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlots>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTableSlotsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createTableSlot = (
    createTableSlotDto: CreateTableSlotDto,
 signal?: AbortSignal
) => {


      return customInstance<TableSlotDto>(
      {url: `/api/table-slots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTableSlotDto, signal
    },
      );
    }



export const getCreateTableSlotMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTableSlot>>, TError,{data: CreateTableSlotDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTableSlot>>, TError,{data: CreateTableSlotDto}, TContext> => {

const mutationKey = ['createTableSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTableSlot>>, {data: CreateTableSlotDto}> = (props) => {
          const {data} = props ?? {};

          return  createTableSlot(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTableSlotMutationResult = NonNullable<Awaited<ReturnType<typeof createTableSlot>>>
    export type CreateTableSlotMutationBody = CreateTableSlotDto
    export type CreateTableSlotMutationError = unknown

    export const useCreateTableSlot = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTableSlot>>, TError,{data: CreateTableSlotDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTableSlot>>,
        TError,
        {data: CreateTableSlotDto},
        TContext
      > => {
      return useMutation(getCreateTableSlotMutationOptions(options), queryClient);
    }
    export const getTableSlotById = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<TableSlotDto>(
      {url: `/api/table-slots/${id}`, method: 'GET', signal
    },
      );
    }




export const getGetTableSlotByIdQueryKey = (id: string,) => {
    return [
    `/api/table-slots/${id}`
    ] as const;
    }


export const getGetTableSlotByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTableSlotById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTableSlotByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTableSlotById>>> = ({ signal }) => getTableSlotById(id, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTableSlotByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTableSlotById>>>
export type GetTableSlotByIdQueryError = unknown


export function useGetTableSlotById<TData = Awaited<ReturnType<typeof getTableSlotById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableSlotById>>,
          TError,
          Awaited<ReturnType<typeof getTableSlotById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableSlotById<TData = Awaited<ReturnType<typeof getTableSlotById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTableSlotById>>,
          TError,
          Awaited<ReturnType<typeof getTableSlotById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTableSlotById<TData = Awaited<ReturnType<typeof getTableSlotById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTableSlotById<TData = Awaited<ReturnType<typeof getTableSlotById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTableSlotById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTableSlotByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const updateTableSlot = (
    id: string,
    updateTableSlotDto: UpdateTableSlotDto,
 signal?: AbortSignal
) => {


      return customInstance<TableSlotDto>(
      {url: `/api/table-slots/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTableSlotDto, signal
    },
      );
    }



export const getUpdateTableSlotMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableSlot>>, TError,{id: string;data: UpdateTableSlotDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTableSlot>>, TError,{id: string;data: UpdateTableSlotDto}, TContext> => {

const mutationKey = ['updateTableSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTableSlot>>, {id: string;data: UpdateTableSlotDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTableSlot(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTableSlotMutationResult = NonNullable<Awaited<ReturnType<typeof updateTableSlot>>>
    export type UpdateTableSlotMutationBody = UpdateTableSlotDto
    export type UpdateTableSlotMutationError = unknown

    export const useUpdateTableSlot = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableSlot>>, TError,{id: string;data: UpdateTableSlotDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTableSlot>>,
        TError,
        {id: string;data: UpdateTableSlotDto},
        TContext
      > => {
      return useMutation(getUpdateTableSlotMutationOptions(options), queryClient);
    }
    export const deleteTableSlot = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/table-slots/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteTableSlotMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTableSlot>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTableSlot>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTableSlot'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTableSlot>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTableSlot(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTableSlotMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTableSlot>>>

    export type DeleteTableSlotMutationError = unknown

    export const useDeleteTableSlot = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTableSlot>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTableSlot>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteTableSlotMutationOptions(options), queryClient);
    }
    export const bulkCreateTableSlots = (
    bulkCreateTableSlotDto: BulkCreateTableSlotDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/table-slots/bulk`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bulkCreateTableSlotDto, signal
    },
      );
    }



export const getBulkCreateTableSlotsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTableSlots>>, TError,{data: BulkCreateTableSlotDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTableSlots>>, TError,{data: BulkCreateTableSlotDto}, TContext> => {

const mutationKey = ['bulkCreateTableSlots'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkCreateTableSlots>>, {data: BulkCreateTableSlotDto}> = (props) => {
          const {data} = props ?? {};

          return  bulkCreateTableSlots(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BulkCreateTableSlotsMutationResult = NonNullable<Awaited<ReturnType<typeof bulkCreateTableSlots>>>
    export type BulkCreateTableSlotsMutationBody = BulkCreateTableSlotDto
    export type BulkCreateTableSlotsMutationError = unknown

    export const useBulkCreateTableSlots = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkCreateTableSlots>>, TError,{data: BulkCreateTableSlotDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkCreateTableSlots>>,
        TError,
        {data: BulkCreateTableSlotDto},
        TContext
      > => {
      return useMutation(getBulkCreateTableSlotsMutationOptions(options), queryClient);
    }
    export const updateTableSlotPosition = (
    id: string,
    tablePositionDto: TablePositionDto,
 signal?: AbortSignal
) => {


      return customInstance<TableSlotDto>(
      {url: `/api/table-slots/${id}/position`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: tablePositionDto, signal
    },
      );
    }



export const getUpdateTableSlotPositionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableSlotPosition>>, TError,{id: string;data: TablePositionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTableSlotPosition>>, TError,{id: string;data: TablePositionDto}, TContext> => {

const mutationKey = ['updateTableSlotPosition'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTableSlotPosition>>, {id: string;data: TablePositionDto}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTableSlotPosition(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTableSlotPositionMutationResult = NonNullable<Awaited<ReturnType<typeof updateTableSlotPosition>>>
    export type UpdateTableSlotPositionMutationBody = TablePositionDto
    export type UpdateTableSlotPositionMutationError = unknown

    export const useUpdateTableSlotPosition = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTableSlotPosition>>, TError,{id: string;data: TablePositionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTableSlotPosition>>,
        TError,
        {id: string;data: TablePositionDto},
        TContext
      > => {
      return useMutation(getUpdateTableSlotPositionMutationOptions(options), queryClient);
    }
