/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * YaoYao Dinner API
 * Restaurant management API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateNoteDto,
  GetNotesByPersonParams
} from '../model';

import { customInstance } from '../../common/axios';




export const getNotesByPerson = (
    params: GetNotesByPersonParams,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/personal-notes`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetNotesByPersonQueryKey = (params?: GetNotesByPersonParams,) => {
    return [
    `/api/personal-notes`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetNotesByPersonQueryOptions = <TData = Awaited<ReturnType<typeof getNotesByPerson>>, TError = unknown>(params: GetNotesByPersonParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotesByPersonQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotesByPerson>>> = ({ signal }) => getNotesByPerson(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotesByPersonQueryResult = NonNullable<Awaited<ReturnType<typeof getNotesByPerson>>>
export type GetNotesByPersonQueryError = unknown


export function useGetNotesByPerson<TData = Awaited<ReturnType<typeof getNotesByPerson>>, TError = unknown>(
 params: GetNotesByPersonParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesByPerson>>,
          TError,
          Awaited<ReturnType<typeof getNotesByPerson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotesByPerson<TData = Awaited<ReturnType<typeof getNotesByPerson>>, TError = unknown>(
 params: GetNotesByPersonParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotesByPerson>>,
          TError,
          Awaited<ReturnType<typeof getNotesByPerson>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotesByPerson<TData = Awaited<ReturnType<typeof getNotesByPerson>>, TError = unknown>(
 params: GetNotesByPersonParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetNotesByPerson<TData = Awaited<ReturnType<typeof getNotesByPerson>>, TError = unknown>(
 params: GetNotesByPersonParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotesByPerson>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotesByPersonQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const createNote = (
    createNoteDto: CreateNoteDto,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/personal-notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createNoteDto, signal
    },
      );
    }



export const getCreateNoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext> => {

const mutationKey = ['createNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNote>>, {data: CreateNoteDto}> = (props) => {
          const {data} = props ?? {};

          return  createNote(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof createNote>>>
    export type CreateNoteMutationBody = CreateNoteDto
    export type CreateNoteMutationError = unknown

    export const useCreateNote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNote>>,
        TError,
        {data: CreateNoteDto},
        TContext
      > => {
      return useMutation(getCreateNoteMutationOptions(options), queryClient);
    }
    export const deleteNote = (
    id: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/personal-notes/${id}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteNoteMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteNote'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNote>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteNote(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNoteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNote>>>

    export type DeleteNoteMutationError = unknown

    export const useDeleteNote = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNote>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNote>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteNoteMutationOptions(options), queryClient);
    }
